In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [12]:
a=np.array([1,2,3.2,4,5])
a

array([1. , 2. , 3.2, 4. , 5. ])

In [8]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
print(a.size)
print(b.size)

5
10


In [15]:
print(a.shape)
print(b.shape)

print(a.dtype)

(5,)
(2, 5)
float64


In [16]:
print(b.transpose)

<built-in method transpose of numpy.ndarray object at 0x000001FE968778D0>


In [28]:
np.empty((4,4),dtype=float)

array([[4.67296746e-307, 1.69121096e-306, 1.95822389e-306,
        2.89265034e-307],
       [1.33511018e-306, 8.34441742e-308, 1.78022342e-306,
        6.23058028e-307],
       [9.79107872e-307, 6.89807188e-307, 7.56594375e-307,
        6.23060065e-307],
       [1.78021527e-306, 8.34454050e-308, 1.11261027e-306,
        2.04712907e-306]])

In [29]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.ones((4,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [39]:
np.ones((5,6),dtype=str)

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [50]:
np.ones((5,6),dtype=bool)

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [51]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [54]:
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [57]:
a=a.reshape((2,5))
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [58]:
a.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
a.ravel()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

ravel only view the original array and if the modification occur and original array also changes

flatten return the copy of the original array and modification not affect the original array