In [1]:
import numpy as np

In [9]:
a=np.arange(1,21).reshape(4,5)
b=np.arange(21,41).reshape(4,5)
print(a,"\n",b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 
 [[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [10]:
a+b

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [13]:
np.add(a,b)

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [14]:
a-b

array([[-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20]])

In [15]:
np.subtract(a,b)

array([[-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20]])

In [16]:
a*b

array([[ 21,  44,  69,  96, 125],
       [156, 189, 224, 261, 300],
       [341, 384, 429, 476, 525],
       [576, 629, 684, 741, 800]])

In [17]:
np.multiply(a,b)

array([[ 21,  44,  69,  96, 125],
       [156, 189, 224, 261, 300],
       [341, 384, 429, 476, 525],
       [576, 629, 684, 741, 800]])

In [18]:
a/b

array([[0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333],
       [0.35483871, 0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949, 0.5       ]])

In [19]:
np.divide(a,b)

array([[0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333],
       [0.35483871, 0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949, 0.5       ]])

a@b --> n*m x m*n = n*n

In [26]:
b=b.reshape(5,4)
b

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40]])

In [27]:
print(a.shape)
print(b.shape)

(4, 5)
(5, 4)


In [28]:
a@b

array([[ 475,  490,  505,  520],
       [1200, 1240, 1280, 1320],
       [1925, 1990, 2055, 2120],
       [2650, 2740, 2830, 2920]])

In [29]:
a.dot(b)

array([[ 475,  490,  505,  520],
       [1200, 1240, 1280, 1320],
       [1925, 1990, 2055, 2120],
       [2650, 2740, 2830, 2920]])

In [30]:
a.min()

1

In [31]:
a.max()

20

In [32]:
a.sum()

210

In [33]:
np.sum(a)

210

In [35]:
np.sum(a,axis=1) #sum of each rows

array([15, 40, 65, 90])

In [37]:
np.mean(a)

10.5

In [39]:
np.sqrt(b)

array([[4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262],
       [5.38516481, 5.47722558, 5.56776436, 5.65685425],
       [5.74456265, 5.83095189, 5.91607978, 6.        ],
       [6.08276253, 6.164414  , 6.244998  , 6.32455532]])

In [40]:
np.std(a)

5.766281297335398

In [41]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227]])